feat: add severity + add tests
mirego/mix_audit pull request #14
Opened 2022-08-23 19:35 UTC by StephaneRob

## 📖 Description and reason

- Add severity to mix audit report
- Add test on formatting

2022-08-23 19:52 UTC, remi requested changes
You’re on 🔥 @StephaneRob! Just a little thing to change and I think it’s ready to merge!

2022-08-23 19:52 UTC, remi commented on lib/mix_audit/formatting/human.ex
> +    #{colorized_text("Severity:", :red)} #{vulnerability.advisory.severity}
I think we should keep the version information as lowest as possible.

```suggestion
    #{colorized_text("Severity:", :red)} #{vulnerability.advisory.severity}
    #{colorized_text("Vulnerable versions:", :red)} #{versions(vulnerability.advisory.vulnerable_version_ranges)}
    #{colorized_text("First patched versions:", :red)} #{versions(vulnerability.advisory.first_patched_versions)}
```

2022-08-23 20:21 UTC, StephaneRob commented
@remi I've changed position of severity info.

2022-08-23 22:00 UTC, remi commented
Awesome!

2022-08-23 22:00 UTC, merged

2022-08-24 00:38 UTC, remi commented
@StephaneRob v2.0.1 will include this new feature!

2022-08-24 07:06 UTC, StephaneRob commented
🔥 thanks @remi!